### ISSUE TITLE
SQLServerException: Invalid column name 'Columns'.

### ISSUE THREAD

**Issue by filippobottega** [janmotl/linkifier#4]
Hi,
  I'm connecting to:

Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64)   Jun 28 2012 08:36:30   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

  Pressing Extimate I get:

```
Successfully connected to the database.
Table count: 62
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'Columns'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:885)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:778)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:677)
	at vendor.MSSQL.getColumnStatistics(MSSQL.java:174)
	at main.Schema.getPrimaryKeys(Schema.java:29)
	at example.Linkifier.estimatePk(Linkifier.java:45)
	at controller.Events$RunService$1.call(Events.java:266)
	at controller.Events$RunService$1.call(Events.java:256)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$null$493(Service.java:725)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$494(Service.java:724)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Something went wrong...

```

  Regards,
    Filippo.

**Comment by janmotl** [comment]
Hi Filippo,

Linkifier 3.2.4 should generate a first row like:
```
Successfully connected to: PredictorFactory.dbo @ Microsoft SQL Server 12.00.600
```
But your first row is:
```
Successfully connected to the database.
```
suggesting an older version of Linkifier.

Can you download Linkifier 3.2.4 from the release page an run Linkifier 3.2.4?

**Comment by filippobottega** [comment]
Thank you!
I was using version 3.1.9...
Version 3.2.4 solved the issue.

Filippo.
