### ISSUE TITLE
SQLServerException: Non è possibile risolvere il conflitto tra le regole di confronto "SQL_Latin1_General_CP850_BIN2" e "Latin1_General_CI_AS" nell'operazione equal to.

### ISSUE THREAD

**Issue by filippobottega** [janmotl/linkifier#5]
Hi,
  if sql server collation is "Latin1_General_CI_AS" but the database collation is different, for example "SQL_Latin1_General_CP850_BIN2" i get the exception:

```
Successfully connected to: MESMID.dbo @ Microsoft SQL Server 14.00.1000
Table count: 61
com.microsoft.sqlserver.jdbc.SQLServerException: Non è possibile risolvere il conflitto tra le regole di confronto "SQL_Latin1_General_CP850_BIN2" e "Latin1_General_CI_AS" nell'operazione equal to.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:885)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:778)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:677)
	at vendor.MSSQL.getColumnStatistics(MSSQL.java:194)
	at main.Schema.getPrimaryKeys(Schema.java:29)
	at example.Linkifier.estimatePk(Linkifier.java:45)
	at controller.Events$RunService$1.call(Events.java:274)
	at controller.Events$RunService$1.call(Events.java:257)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javafx.concurrent.Service.lambda$null$493(Service.java:725)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$494(Service.java:724)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Something went wrong...
Linkifier version: 3.2.4
Please, send an email to the developer at jan.motl@fit.cvut.cz
```

   Regards,
    Filippo.

**Comment by janmotl** [comment]
Thank you for the bug report.

New Linkifier 3.2.5 solves the problem by using ``database_default`` keyword in the SQL query.

**Comment by filippobottega** [comment]
Thank you!
New version solved the issue.

Regards,
Filippo.
